version: '3'

services:

  utils:
    #build: src/utils
    image: ace5040/utils:stable
    container_name: utils

  sitesbox:
    #build: src/sitesbox
    image: ace5040/sitesbox:stable
    container_name: sitesbox
    hostname: sitesbox
    restart: unless-stopped
    dns:
      - 172.31.0.100
    ports:
      - "2222:22"
      #- "21:21"
      #- "20:20"
      #- "50000-50100:50000-50100"
      - "${DNSMASQ_PORT-5353}:53/udp"
    environment:
      - MODE=${SITESBOX_MODE} #set MODE DEV or PRODUCTION
      - SITES_PATH=${SITES_PATH}
      - DEV_MODE_USER_PASS=${DEV_MODE_USER_PASS} #password for dev user
      - DEV_MODE_USER_UID=${DEV_MODE_USER_UID} #UID for dev user set it to your HOSTs user UID
      - DEV_MODE_USER_GID=${DEV_MODE_USER_GID} #GID for dev user set it to your HOSTs user GID
      - PHPMYADMIN_DNS_NAME=${PHPMYADMIN_DNS_NAME} #phpmyadmin dns name
      - DOCKER_HOST_IP=${DOCKER_HOST_IP} #ip for dnsmasq service
      - SITESBOX_EXTERNAL_DNS_IP=${SITESBOX_EXTERNAL_DNS_IP}
    volumes:
      - ${SITES_PATH}:/sites
      - /etc/localtime:/etc/localtime:ro
      - ./config/crontabs:/var/spool/cron
      - ./config/telegraf:/etc/telegraf/telegraf.d:ro
      - ./sites:/sitesbox/sites_configs:ro
      #- ./users:/sitesbox/users:ro
      - ./config/ssh:/sitesbox/ssh_keys
      - ./config/php-pool-templates:/sitesbox/custom_templates:ro
      - ./config/php/php7.ini:/etc/php/conf.d/user.ini:ro
      - ./config/php/php73.ini:/etc/php73/conf.d/user.ini:ro
      - ./config/php/php5.ini:/etc/php56/conf.d/user.ini:ro
      - ./config/exim/exim.conf:/etc/mail/exim.conf
      - ./config/letsencrypt:/etc/letsencrypt
      - php7_pools_volume:/etc/php/php-fpm.d
      - php73_pools_volume:/etc/php73/php-fpm.d
      - php5_pools_volume:/etc/php56/php-fpm.d
      - dnsmasq_hosts_volume:/sitesbox/dnsmasq_hosts
      - nginx_configs_volume:/sitesbox/nginx_configs
      - phpmyadmin_volume:/phpmyadmin
      - phpmyadmin_config_volume:/etc/phpmyadmin
      - ${PATH_TO_PASSWD_FILE}:/sitesbox/passwd:ro
      - ${PATH_TO_SHADOW_FILE}:/sitesbox/shadow:ro
    networks:
      network:
        ipv4_address: 172.31.0.100

  nginx:
    #build: src/nginx
    image: ace5040/nginx:stable
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - SITESBOX_MODE=${SITESBOX_MODE} #set MODE DEV or PRODUCTION
      - DEV_MODE_USER_GID=${DEV_MODE_USER_GID} #GID for dev user set it to your HOSTs user GID
    volumes:
      - ${SITES_PATH}:/sites
      - /etc/localtime:/etc/localtime:ro
      - ./config/letsencrypt:/etc/letsencrypt:ro
      - nginx_configs_volume:/etc/nginx/conf.d:ro
      - ${PATH_TO_GROUP_FILE}:/sitesbox/group:ro
      - phpmyadmin_volume:/phpmyadmin
    depends_on:
      - "sitesbox"
    networks:
      - network

  memcache:
    image: memcached
    container_name: memcache
    hostname: memcache
    restart: unless-stopped
    networks:
      - network

  mysql5:
    image: mariadb:5
    container_name: mysql5
    restart: unless-stopped
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql #change password after first run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_TO_MYSQL5_DB}:/var/lib/mysql #path to mysql5 databases
      - ${PATH_TO_MYSQL5_CONFIG}:/etc/mysql/conf.d/user.cnf
    networks:
      - network

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql #change password after first run
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_TO_MYSQL_DB}:/var/lib/mysql #path to mysql5 databases
      - ${PATH_TO_MYSQL_CONFIG}:/etc/mysql/conf.d/user.cnf
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=mysql,mysql5
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sessions
      - phpmyadmin_volume:/var/www/html
      - phpmyadmin_config_volume:/etc/phpmyadmin
    networks:
      - network

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ${PATH_TO_POSTGRES_DB}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - network

  phppgadmin:
    image: dockage/phppgadmin
    container_name: phppgadmin
    restart: unless-stopped
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
    ports:
      - 8081:80
    networks:
      - network

  doctohtml:
    image: ace5040/doctohtml:latest
    container_name: doctohtml
    hostname: doctohtml
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - network

  htmltopdf:
    dns:
      - 172.31.0.100
    #build: ../projects/htmltopdf
    image: ace5040/htmltopdf:latest
    container_name: htmltopdf
    hostname: htmltopdf
    restart: unless-stopped
    ports:
      - 3001:3000
    networks:
      - network

  solr:
    image: solr:6
    container_name: solr
    restart: unless-stopped
    ports:
     - "8983:8983"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SOLR_CORES_PATH}:/opt/solr/server/solr/mycores #path to solr cores
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - -f
    networks:
      - network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "8181:3000"
    environment:
      GF_PATHS_DATA: /data
      GF_PATHS_LOGS: /log
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/grafana/data:/data
    networks:
      - network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      INFLUXDB_DB: telegraf
    ports:
      - "8086:8086"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/influxdb:/var/lib/influxdb
    networks:
      - network

volumes:
  dnsmasq_hosts_volume: {}
  nginx_configs_volume: {}
  php7_pools_volume: {}
  php73_pools_volume: {}
  php5_pools_volume: {}
  phpmyadmin_volume: {}
  phpmyadmin_config_volume: {}

networks:
  network:
    ipam:
      config:
        - subnet: 172.31.0.0/16
