version: '3'

services:

  webcrate-utils:
    build: src/webcrate-utils
    image: ace5040/webcrate-utils:stable
    container_name: webcrate-utils
    networks:
      - network

  webcrate-core:
    build: src/webcrate-core
    image: ace5040/webcrate-core:stable
    container_name: webcrate-core
    hostname: webcrate-core
    restart: unless-stopped
    dns:
      - 172.31.0.100
    ports:
      - "2222:22"
      - "21:21"
      - "20:20"
      - "50000-50100:50000-50100"
      - "${DNSMASQ_PORT-5353}:53/udp"
    environment:
      - WEBCRATE_UID=${WEBCRATE_UID}
      - WEBCRATE_GID=${WEBCRATE_GID}
      - WEBCRATE_MODE=${WEBCRATE_MODE}
      - DEV_MODE_USER_PASS=${DEV_MODE_USER_PASS}
      - WEBCRATE_EXTERNAL_DNS_IP=${WEBCRATE_EXTERNAL_DNS_IP}
      - UID_START_NUMBER=${UID_START_NUMBER}
      - CGI_PORT_START_NUMBER=${CGI_PORT_START_NUMBER}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SITES_PATH}:/sites
      - ./var/crontabs:/var/spool/cron
      - ./config/telegraf:/etc/telegraf/telegraf.d:ro
      - ./users.yml:/webcrate/users.yml:ro
      - ./var/ssh:/webcrate/ssh_keys
      - ./config/php-pool-templates:/webcrate/custom_templates:ro
      - ./config/php/php7.ini:/etc/php/conf.d/user.ini:ro
      - ./config/php/php73.ini:/etc/php73/conf.d/user.ini:ro
      - ./config/php/php5.ini:/etc/php56/conf.d/user.ini:ro
      - ./config/exim/exim.conf:/etc/mail/exim.conf
      - php7_pools:/etc/php/php-fpm.d
      - php73_pools:/etc/php73/php-fpm.d
      - php5_pools:/etc/php56/php-fpm.d
      - dnsmasq_hosts:/webcrate/dnsmasq_hosts
    networks:
      network:
        ipv4_address: 172.31.0.100

  webcrate-tools:
    build: src/webcrate-tools
    image: ace5040/webcrate-tools:stable
    container_name: webcrate-tools
    hostname: webcrate-tools
    restart: unless-stopped
    environment:
      - WEBCRATE_UID=${WEBCRATE_UID}
      - WEBCRATE_GID=${WEBCRATE_GID}
      - WEBCRATE_MODE=${WEBCRATE_MODE}
      - REMOTE_BACKUP_URI=${REMOTE_BACKUP_URI}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - WEBCRATE_EXTERNAL_DNS_IP=${WEBCRATE_EXTERNAL_DNS_IP}
    volumes:
      - ${SITES_PATH}:/sites
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ./users.yml:/webcrate/users.yml:ro
      - ./var/letsencrypt:/webcrate/letsencrypt
      - ./var/backup:/webcrate/backup
      - ./var/secrets:/webcrate/secrets
      - ./var/duplicity:/webcrate/duplicity
      - ssl_configs:/webcrate/ssl_configs
    depends_on:
      - "webcrate-core"
      - "webcrate-nginx"
      - "mysql"
      - "mysql5"
      - "postgres"
    networks:
      - network

  webcrate-nginx:
    build: src/webcrate-nginx
    image: ace5040/webcrate-nginx:stable
    container_name: webcrate-nginx
    hostname: webcrate-nginx
    restart: unless-stopped
    ports:
      - "80:1080"
      - "443:1443"
    environment:
      - WEBCRATE_MODE=${WEBCRATE_MODE}
      - WEBCRATE_UID=${WEBCRATE_UID}
      - WEBCRATE_GID=${WEBCRATE_GID}
    volumes:
      - ${SITES_PATH}:/sites
      - /etc/localtime:/etc/localtime:ro
      - ./users.yml:/webcrate/users.yml:ro
      - ./var/letsencrypt:/webcrate/letsencrypt:ro
      - ssl_configs:/webcrate/ssl_configs:ro
      - nginx_configs:/etc/nginx/conf.d:ro
    depends_on:
      - "webcrate-core"
    networks:
      - network

  memcache:
    image: memcached
    container_name: memcache
    hostname: memcache
    restart: unless-stopped
    networks:
      - network

  mysql5:
    image: mariadb:5
    container_name: mysql5
    restart: unless-stopped
    user: "${WEBCRATE_UID}:${WEBCRATE_GID}"
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL5_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/mysql5:/var/lib/mysql
      - ./config/mysql/mysql5.cnf:/etc/mysql/conf.d/user.cnf
    networks:
      - network

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    user: "${WEBCRATE_UID}:${WEBCRATE_GID}"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/mysql:/var/lib/mysql
      - ./config/mysql/mysql.cnf:/etc/mysql/conf.d/user.cnf
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    logging:
      driver: none
    container_name: phpmyadmin
    environment:
      - PMA_HOSTS=mysql,mysql5
      - UPLOAD_LIMIT=2048M
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/phpmyadmin/php.ini:/usr/local/etc/php/php.ini
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - phpmyadmin_sessions:/sessions
      - phpmyadmin:/var/www/html
      - phpmyadmin_config:/etc/phpmyadmin
    networks:
      - network

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    user: "${WEBCRATE_UID}:${WEBCRATE_GID}"
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - network

  phppgadmin:
    image: dockage/phppgadmin
    container_name: phppgadmin
    restart: unless-stopped
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
    volumes:
      - phppgadmin:/data
      - phppgadmin_logs:/var/log
    networks:
      - network

  doctohtml:
    image: ace5040/doctohtml:latest
    container_name: doctohtml
    hostname: doctohtml
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - network

  htmltopdf:
    dns:
      - 172.31.0.100
    build: ../projects/htmltopdf
    image: ace5040/htmltopdf:latest
    container_name: htmltopdf
    hostname: htmltopdf
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - network

  solr:
    image: solr:6
    container_name: solr
    restart: unless-stopped
    user: "${WEBCRATE_UID}:${WEBCRATE_GID}"
    logging:
      driver: none
    ports:
     - "8983:8983"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/solr/logs:/opt/solr/server/logs
      - ./var/solr/cores:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - -force
      - -f
    networks:
      - network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "${WEBCRATE_UID}:${WEBCRATE_GID}"
    logging:
      driver: none
    ports:
      - "8181:3000"
    environment:
      GF_PATHS_DATA: /data
      GF_PATHS_LOGS: /log
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /home.json
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/grafana/data:/data
      - ./var/grafana/log:/log
      - ./config/grafana/home.json:/home.json
      - ./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yml
    networks:
      - network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    user: "${WEBCRATE_UID}:${WEBCRATE_GID}"
    logging:
      driver: none
    environment:
      INFLUXDB_DB: telegraf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./var/influxdb:/var/lib/influxdb
    networks:
      - network

volumes:
  dnsmasq_hosts: {}
  nginx_configs: {}
  ssl_configs: {}
  php7_pools: {}
  php73_pools: {}
  php5_pools: {}
  phpmyadmin: {}
  phpmyadmin_config: {}
  phpmyadmin_sessions: {}
  phppgadmin: {}
  phppgadmin_logs: {}

networks:
  network:
    ipam:
      config:
        - subnet: 172.31.0.0/16
